# Generated by Django 4.2 on 2023-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_added',
            field=models.ManyToManyField(related_name='books_added', to='books.book'),
        ),
    ]
