# Generated by Django 4.2 on 2023-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0002_user_books_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_added',
            field=models.ManyToManyField(blank=True, related_name='books_added', to='books.book'),
        ),
    ]
