# Generated by Django 4.2 on 2023-04-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bookstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_added',
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
