# Generated by Django 4.2 on 2023-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_status'),
        ('users', '0006_remove_user_books_added_delete_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_added',
            field=models.ManyToManyField(related_name='books_added', to='books.book'),
        ),
    ]
