# Generated by Django 4.2 on 2023-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_status'),
        ('users', '0007_user_books_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_added',
        ),
        migrations.AddField(
            model_name='user',
            name='read',
            field=models.ManyToManyField(related_name='read', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='reading',
            field=models.ManyToManyField(related_name='reading', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='books.book'),
        ),
    ]
