# Generated by Django 4.2 on 2023-04-23 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_read_alter_user_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
