# Generated by Django 4.2 on 2023-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reading_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
