# Generated by Django 4.2 on 2023-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('pages', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('read', 'Read'), ('reading', 'Reading'), ('wishlist', 'Wishlist')], max_length=10)),
            ],
        ),
    ]
