# Generated by Django 4.2 on 2023-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading', 'Reading'), ('wishlist', 'Wishlist'), ('none', 'None')], max_length=10),
        ),
    ]
